#!/usr/bin/env ruby

require 'rubygems'
require 'net/dns/resolver'
require 'lib/dnschecker'

dnschecker = Dnschecker.new
domain_list = dnschecker.domain_list_from_file(ARGV[0])

domain_list.each do |domain|
  dnschecker.check_name(domain)
  dnschecker.check_name("www.#{domain}")
end
